//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paths
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses_data
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> sub_path_id { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> comments_count { get; set; }
        public Nullable<int> added_by { get; set; }
        public string icon { get; set; }
        public string Course_link { get; set; }
    
        public virtual sub_path_data sub_path_data { get; set; }
        public virtual sub_path_data sub_path_data1 { get; set; }
        public virtual sub_path_data sub_path_data2 { get; set; }
        public virtual sub_path_data sub_path_data3 { get; set; }
        public virtual sub_path_data sub_path_data4 { get; set; }
        public virtual sub_path_data sub_path_data5 { get; set; }
        public virtual sub_path_data sub_path_data6 { get; set; }
        public virtual sub_path_data sub_path_data7 { get; set; }
        public virtual sub_path_data sub_path_data8 { get; set; }
        public virtual sub_path_data sub_path_data9 { get; set; }
        public virtual sub_path_data sub_path_data10 { get; set; }
    }
}
