//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paths
{
    using System;
    using System.Collections.Generic;
    
    public partial class path_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public path_data()
        {
            this.sub_path_data = new HashSet<sub_path_data>();
            this.sub_path_data1 = new HashSet<sub_path_data>();
            this.sub_path_data2 = new HashSet<sub_path_data>();
            this.sub_path_data3 = new HashSet<sub_path_data>();
            this.sub_path_data4 = new HashSet<sub_path_data>();
            this.sub_path_data5 = new HashSet<sub_path_data>();
            this.sub_path_data6 = new HashSet<sub_path_data>();
            this.sub_path_data7 = new HashSet<sub_path_data>();
            this.sub_path_data8 = new HashSet<sub_path_data>();
            this.sub_path_data9 = new HashSet<sub_path_data>();
            this.sub_path_data10 = new HashSet<sub_path_data>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string about { get; set; }
        public string to_learn { get; set; }
        public Nullable<int> rate { get; set; }
        public string details { get; set; }
        public string Pic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sub_path_data> sub_path_data10 { get; set; }
    }
}
